package trivalibs.preact.html

import trivalibs.preact.component.AttributeModifier
import org.scalajs.dom
import scala.scalajs.js

// DO NOT EDIT - Generated from scala-dom-types
// See codegen/HtmlCodegen.scala

object HtmlEvents:
  type OnClick = AttributeModifier["onClick", js.Function1[dom.MouseEvent, Unit]]
  type OnDblClick = AttributeModifier["onDblClick", js.Function1[dom.MouseEvent, Unit]]
  type OnMouseDown = AttributeModifier["onMouseDown", js.Function1[dom.MouseEvent, Unit]]
  type OnMouseMove = AttributeModifier["onMouseMove", js.Function1[dom.MouseEvent, Unit]]
  type OnMouseOut = AttributeModifier["onMouseOut", js.Function1[dom.MouseEvent, Unit]]
  type OnMouseOver = AttributeModifier["onMouseOver", js.Function1[dom.MouseEvent, Unit]]
  type OnMouseLeave = AttributeModifier["onMouseLeave", js.Function1[dom.MouseEvent, Unit]]
  type OnMouseEnter = AttributeModifier["onMouseEnter", js.Function1[dom.MouseEvent, Unit]]
  type OnMouseUp = AttributeModifier["onMouseUp", js.Function1[dom.MouseEvent, Unit]]
  type OnWheel = AttributeModifier["onWheel", js.Function1[dom.WheelEvent, Unit]]
  type OnContextMenu = AttributeModifier["onContextMenu", js.Function1[dom.MouseEvent, Unit]]
  type OnDrag = AttributeModifier["onDrag", js.Function1[dom.DragEvent, Unit]]
  type OnDragEnd = AttributeModifier["onDragEnd", js.Function1[dom.DragEvent, Unit]]
  type OnDragEnter = AttributeModifier["onDragEnter", js.Function1[dom.DragEvent, Unit]]
  type OnDragLeave = AttributeModifier["onDragLeave", js.Function1[dom.DragEvent, Unit]]
  type OnDragOver = AttributeModifier["onDragOver", js.Function1[dom.DragEvent, Unit]]
  type OnDragStart = AttributeModifier["onDragStart", js.Function1[dom.DragEvent, Unit]]
  type OnDrop = AttributeModifier["onDrop", js.Function1[dom.DragEvent, Unit]]
  type OnKeyDown = AttributeModifier["onKeyDown", js.Function1[dom.KeyboardEvent, Unit]]
  type OnKeyUp = AttributeModifier["onKeyUp", js.Function1[dom.KeyboardEvent, Unit]]
  type OnKeyPress = AttributeModifier["onKeyPress", js.Function1[dom.KeyboardEvent, Unit]]
  type OnChange = AttributeModifier["onChange", js.Function1[dom.Event, Unit]]
  type OnSelect = AttributeModifier["onSelect", js.Function1[dom.Event, Unit]]
  type OnBeforeInput = AttributeModifier["onBeforeInput", js.Function1[dom.InputEvent, Unit]]
  type OnInput = AttributeModifier["onInput", js.Function1[dom.Event, Unit]]
  type OnBlur = AttributeModifier["onBlur", js.Function1[dom.FocusEvent, Unit]]
  type OnFocus = AttributeModifier["onFocus", js.Function1[dom.FocusEvent, Unit]]
  type OnSubmit = AttributeModifier["onSubmit", js.Function1[dom.Event, Unit]]
  type OnReset = AttributeModifier["onReset", js.Function1[dom.Event, Unit]]
  type OnInvalid = AttributeModifier["onInvalid", js.Function1[dom.Event, Unit]]
  type OnSearch = AttributeModifier["onSearch", js.Function1[dom.Event, Unit]]
  type OnCopy = AttributeModifier["onCopy", js.Function1[dom.ClipboardEvent, Unit]]
  type OnCut = AttributeModifier["onCut", js.Function1[dom.ClipboardEvent, Unit]]
  type OnPaste = AttributeModifier["onPaste", js.Function1[dom.ClipboardEvent, Unit]]
  type OnTouchStart = AttributeModifier["onTouchStart", js.Function1[dom.TouchEvent, Unit]]
  type OnTouchMove = AttributeModifier["onTouchMove", js.Function1[dom.TouchEvent, Unit]]
  type OnTouchCancel = AttributeModifier["onTouchCancel", js.Function1[dom.TouchEvent, Unit]]
  type OnTouchEnd = AttributeModifier["onTouchEnd", js.Function1[dom.TouchEvent, Unit]]
  type OnPointerOver = AttributeModifier["onPointerOver", js.Function1[dom.PointerEvent, Unit]]
  type OnPointerEnter = AttributeModifier["onPointerEnter", js.Function1[dom.PointerEvent, Unit]]
  type OnPointerDown = AttributeModifier["onPointerDown", js.Function1[dom.PointerEvent, Unit]]
  type OnPointerMove = AttributeModifier["onPointerMove", js.Function1[dom.PointerEvent, Unit]]
  type OnPointerUp = AttributeModifier["onPointerUp", js.Function1[dom.PointerEvent, Unit]]
  type OnPointerCancel = AttributeModifier["onPointerCancel", js.Function1[dom.PointerEvent, Unit]]
  type OnPointerOut = AttributeModifier["onPointerOut", js.Function1[dom.PointerEvent, Unit]]
  type OnPointerLeave = AttributeModifier["onPointerLeave", js.Function1[dom.PointerEvent, Unit]]
  type GotPointerCapture = AttributeModifier["gotPointerCapture", js.Function1[dom.PointerEvent, Unit]]
  type LostPointerCapture = AttributeModifier["lostPointerCapture", js.Function1[dom.PointerEvent, Unit]]
  type OnAnimationEnd = AttributeModifier["onAnimationEnd", js.Function1[dom.AnimationEvent, Unit]]
  type OnAnimationIteration = AttributeModifier["onAnimationIteration", js.Function1[dom.AnimationEvent, Unit]]
  type OnAnimationStart = AttributeModifier["onAnimationStart", js.Function1[dom.AnimationEvent, Unit]]
  type OnTransitionEnd = AttributeModifier["onTransitionEnd", js.Function1[dom.Event, Unit]]
  type OnAbort = AttributeModifier["onAbort", js.Function1[dom.Event, Unit]]
  type OnCanPlay = AttributeModifier["onCanPlay", js.Function1[dom.Event, Unit]]
  type OnCanPlayThrough = AttributeModifier["onCanPlayThrough", js.Function1[dom.Event, Unit]]
  type OnCueChange = AttributeModifier["onCueChange", js.Function1[dom.Event, Unit]]
  type OnDurationChange = AttributeModifier["onDurationChange", js.Function1[dom.Event, Unit]]
  type OnEmptied = AttributeModifier["onEmptied", js.Function1[dom.Event, Unit]]
  type OnEnded = AttributeModifier["onEnded", js.Function1[dom.Event, Unit]]
  type OnLoadedData = AttributeModifier["onLoadedData", js.Function1[dom.Event, Unit]]
  type OnLoadedMetadata = AttributeModifier["onLoadedMetadata", js.Function1[dom.Event, Unit]]
  type OnLoadStart = AttributeModifier["onLoadStart", js.Function1[dom.Event, Unit]]
  type OnPause = AttributeModifier["onPause", js.Function1[dom.Event, Unit]]
  type OnPlay = AttributeModifier["onPlay", js.Function1[dom.Event, Unit]]
  type OnPlaying = AttributeModifier["onPlaying", js.Function1[dom.Event, Unit]]
  type OnProgress = AttributeModifier["onProgress", js.Function1[dom.Event, Unit]]
  type OnRateChange = AttributeModifier["onRateChange", js.Function1[dom.Event, Unit]]
  type OnSeeked = AttributeModifier["onSeeked", js.Function1[dom.Event, Unit]]
  type OnSeeking = AttributeModifier["onSeeking", js.Function1[dom.Event, Unit]]
  type OnStalled = AttributeModifier["onStalled", js.Function1[dom.Event, Unit]]
  type OnSuspend = AttributeModifier["onSuspend", js.Function1[dom.Event, Unit]]
  type OnTimeUpdate = AttributeModifier["onTimeUpdate", js.Function1[dom.Event, Unit]]
  type OnVolumeChange = AttributeModifier["onVolumeChange", js.Function1[dom.Event, Unit]]
  type OnWaiting = AttributeModifier["onWaiting", js.Function1[dom.Event, Unit]]
  type OnLoad = AttributeModifier["onLoad", js.Function1[dom.UIEvent, Unit]]
  type OnResize = AttributeModifier["onResize", js.Function1[dom.UIEvent, Unit]]
  type OnScroll = AttributeModifier["onScroll", js.Function1[dom.UIEvent, Unit]]
  type OnSelectStart = AttributeModifier["onSelectStart", js.Function1[dom.Event, Unit]]
  type OnShow = AttributeModifier["onShow", js.Function1[dom.Event, Unit]]
  type OnToggle = AttributeModifier["onToggle", js.Function1[dom.Event, Unit]]
  type OnError = AttributeModifier["onError", js.Function1[dom.ErrorEvent, Unit]]
