package trivalibs.preact.html

import trivalibs.preact.component.ChildModifier

// DO NOT EDIT - Generated from scala-dom-types
// See codegen/HtmlCodegen.scala

object HtmlModifiers:
  type Modifier =
    HtmlAttrs.Key |
    HtmlAttrs.Cls |
    HtmlAttrs.Typ |
    HtmlAttrs.Rel |
    HtmlAttrs.Accept |
    HtmlAttrs.AccessKey |
    HtmlAttrs.Action |
    HtmlAttrs.Alt |
    HtmlAttrs.AutoCapitalize |
    HtmlAttrs.AutoComplete |
    HtmlAttrs.AutoFocus |
    HtmlAttrs.Charset |
    HtmlAttrs.ColSpan |
    HtmlAttrs.Cols |
    HtmlAttrs.ContentAttr |
    HtmlAttrs.ContentEditable |
    HtmlAttrs.ContextMenuId |
    HtmlAttrs.CrossOrigin |
    HtmlAttrs.DefaultChecked |
    HtmlAttrs.DefaultSelected |
    HtmlAttrs.DefaultValue |
    HtmlAttrs.Dir |
    HtmlAttrs.Disabled |
    HtmlAttrs.Download |
    HtmlAttrs.Draggable |
    HtmlAttrs.DropZone |
    HtmlAttrs.EncType |
    HtmlAttrs.ForId |
    HtmlAttrs.FormAction |
    HtmlAttrs.FormEncType |
    HtmlAttrs.FormId |
    HtmlAttrs.FormMethod |
    HtmlAttrs.FormNoValidate |
    HtmlAttrs.FormTarget |
    HtmlAttrs.HeightAttr |
    HtmlAttrs.Hidden |
    HtmlAttrs.High |
    HtmlAttrs.Href |
    HtmlAttrs.HttpEquiv |
    HtmlAttrs.IdAttr |
    HtmlAttrs.InputMode |
    HtmlAttrs.LabelAttr |
    HtmlAttrs.Lang |
    HtmlAttrs.ListId |
    HtmlAttrs.LoadingAttr |
    HtmlAttrs.Low |
    HtmlAttrs.MaxAttr |
    HtmlAttrs.MaxLength |
    HtmlAttrs.Media |
    HtmlAttrs.Method |
    HtmlAttrs.MinAttr |
    HtmlAttrs.MinLength |
    HtmlAttrs.Multiple |
    HtmlAttrs.NameAttr |
    HtmlAttrs.NoValidate |
    HtmlAttrs.Optimum |
    HtmlAttrs.Pattern |
    HtmlAttrs.Placeholder |
    HtmlAttrs.ReadOnly |
    HtmlAttrs.Required |
    HtmlAttrs.RowSpan |
    HtmlAttrs.Rows |
    HtmlAttrs.Scoped |
    HtmlAttrs.Size |
    HtmlAttrs.Slot |
    HtmlAttrs.SpellCheck |
    HtmlAttrs.Src |
    HtmlAttrs.StepAttr |
    HtmlAttrs.TabIndex |
    HtmlAttrs.Target |
    HtmlAttrs.Title |
    HtmlAttrs.Translate |
    HtmlAttrs.Unselectable |
    HtmlAttrs.WidthAttr |
    HtmlAttrs.Xmlns |
    HtmlEvents.OnClick |
    HtmlEvents.OnDblClick |
    HtmlEvents.OnMouseDown |
    HtmlEvents.OnMouseMove |
    HtmlEvents.OnMouseOut |
    HtmlEvents.OnMouseOver |
    HtmlEvents.OnMouseLeave |
    HtmlEvents.OnMouseEnter |
    HtmlEvents.OnMouseUp |
    HtmlEvents.OnWheel |
    HtmlEvents.OnContextMenu |
    HtmlEvents.OnDrag |
    HtmlEvents.OnDragEnd |
    HtmlEvents.OnDragEnter |
    HtmlEvents.OnDragLeave |
    HtmlEvents.OnDragOver |
    HtmlEvents.OnDragStart |
    HtmlEvents.OnDrop |
    HtmlEvents.OnKeyDown |
    HtmlEvents.OnKeyUp |
    HtmlEvents.OnKeyPress |
    HtmlEvents.OnChange |
    HtmlEvents.OnSelect |
    HtmlEvents.OnBeforeInput |
    HtmlEvents.OnInput |
    HtmlEvents.OnBlur |
    HtmlEvents.OnFocus |
    HtmlEvents.OnSubmit |
    HtmlEvents.OnReset |
    HtmlEvents.OnInvalid |
    HtmlEvents.OnSearch |
    HtmlEvents.OnCopy |
    HtmlEvents.OnCut |
    HtmlEvents.OnPaste |
    HtmlEvents.OnTouchStart |
    HtmlEvents.OnTouchMove |
    HtmlEvents.OnTouchCancel |
    HtmlEvents.OnTouchEnd |
    HtmlEvents.OnPointerOver |
    HtmlEvents.OnPointerEnter |
    HtmlEvents.OnPointerDown |
    HtmlEvents.OnPointerMove |
    HtmlEvents.OnPointerUp |
    HtmlEvents.OnPointerCancel |
    HtmlEvents.OnPointerOut |
    HtmlEvents.OnPointerLeave |
    HtmlEvents.GotPointerCapture |
    HtmlEvents.LostPointerCapture |
    HtmlEvents.OnAnimationEnd |
    HtmlEvents.OnAnimationIteration |
    HtmlEvents.OnAnimationStart |
    HtmlEvents.OnTransitionEnd |
    HtmlEvents.OnAbort |
    HtmlEvents.OnCanPlay |
    HtmlEvents.OnCanPlayThrough |
    HtmlEvents.OnCueChange |
    HtmlEvents.OnDurationChange |
    HtmlEvents.OnEmptied |
    HtmlEvents.OnEnded |
    HtmlEvents.OnLoadedData |
    HtmlEvents.OnLoadedMetadata |
    HtmlEvents.OnLoadStart |
    HtmlEvents.OnPause |
    HtmlEvents.OnPlay |
    HtmlEvents.OnPlaying |
    HtmlEvents.OnProgress |
    HtmlEvents.OnRateChange |
    HtmlEvents.OnSeeked |
    HtmlEvents.OnSeeking |
    HtmlEvents.OnStalled |
    HtmlEvents.OnSuspend |
    HtmlEvents.OnTimeUpdate |
    HtmlEvents.OnVolumeChange |
    HtmlEvents.OnWaiting |
    HtmlEvents.OnLoad |
    HtmlEvents.OnResize |
    HtmlEvents.OnScroll |
    HtmlEvents.OnSelectStart |
    HtmlEvents.OnShow |
    HtmlEvents.OnToggle |
    HtmlEvents.OnError |
    ChildModifier
