package trivalibs.preact.html

import trivalibs.preact.component.AttributeModifier
import trivalibs.utils.js.*

// DO NOT EDIT - Generated from scala-dom-types
// See codegen/HtmlCodegen.scala

object HtmlAttrs:
  // Special attributes (manually defined, not in scala-dom-types)
  type Key = AttributeModifier["key", String]
  type Cls = AttributeModifier["cls", Opt[String]]
  type Typ = AttributeModifier["type", String]  // `type` is a reserved word in Scala
  type Rel = AttributeModifier["rel", String]   // Link relationship type

  // Generated reflected HTML attributes
  type Accept = AttributeModifier["accept", String]
  type AccessKey = AttributeModifier["accesskey", String]
  type Action = AttributeModifier["action", String]
  type Alt = AttributeModifier["alt", String]
  type AutoCapitalize = AttributeModifier["autocapitalize", String]
  type AutoComplete = AttributeModifier["autocomplete", String]
  type AutoFocus = AttributeModifier["autofocus", Boolean]
  type Charset = AttributeModifier["charset", String]
  type ColSpan = AttributeModifier["colspan", Int]
  type Cols = AttributeModifier["cols", Int]
  type ContentAttr = AttributeModifier["content", String]
  type ContentEditable = AttributeModifier["contenteditable", Boolean]
  type ContextMenuId = AttributeModifier["contextmenu", String]
  type CrossOrigin = AttributeModifier["crossorigin", String]
  type DefaultChecked = AttributeModifier["checked", Boolean]
  type DefaultSelected = AttributeModifier["selected", Boolean]
  type DefaultValue = AttributeModifier["value", String]
  type Dir = AttributeModifier["dir", String]
  type Disabled = AttributeModifier["disabled", Boolean]
  type Download = AttributeModifier["download", String]
  type Draggable = AttributeModifier["draggable", Boolean]
  type DropZone = AttributeModifier["dropzone", String]
  type EncType = AttributeModifier["enctype", String]
  type ForId = AttributeModifier["for", String]
  type FormAction = AttributeModifier["formaction", String]
  type FormEncType = AttributeModifier["formenctype", String]
  type FormId = AttributeModifier["form", String]
  type FormMethod = AttributeModifier["formmethod", String]
  type FormNoValidate = AttributeModifier["formnovalidate", Boolean]
  type FormTarget = AttributeModifier["formtarget", String]
  type HeightAttr = AttributeModifier["height", Int]
  type Hidden = AttributeModifier["hidden", Boolean]
  type High = AttributeModifier["high", Double]
  type Href = AttributeModifier["href", String]
  type HttpEquiv = AttributeModifier["http-equiv", String]
  type IdAttr = AttributeModifier["id", String]
  type InputMode = AttributeModifier["inputmode", String]
  type LabelAttr = AttributeModifier["label", String]
  type Lang = AttributeModifier["lang", String]
  type ListId = AttributeModifier["list", String]
  type LoadingAttr = AttributeModifier["loading", String]
  type Low = AttributeModifier["low", Double]
  type MaxAttr = AttributeModifier["max", String]
  type MaxLength = AttributeModifier["maxlength", Int]
  type Media = AttributeModifier["media", String]
  type Method = AttributeModifier["method", String]
  type MinAttr = AttributeModifier["min", String]
  type MinLength = AttributeModifier["minlength", Int]
  type Multiple = AttributeModifier["multiple", Boolean]
  type NameAttr = AttributeModifier["name", String]
  type NoValidate = AttributeModifier["novalidate", Boolean]
  type Optimum = AttributeModifier["optimum", Double]
  type Pattern = AttributeModifier["pattern", String]
  type Placeholder = AttributeModifier["placeholder", String]
  type ReadOnly = AttributeModifier["readonly", Boolean]
  type Required = AttributeModifier["required", Boolean]
  type RowSpan = AttributeModifier["rowspan", Int]
  type Rows = AttributeModifier["rows", Int]
  type Scoped = AttributeModifier["scoped", Boolean]
  type Size = AttributeModifier["size", Int]
  type Slot = AttributeModifier["slot", String]
  type SpellCheck = AttributeModifier["spellcheck", Boolean]
  type Src = AttributeModifier["src", String]
  type StepAttr = AttributeModifier["step", String]
  type TabIndex = AttributeModifier["tabindex", Int]
  type Target = AttributeModifier["target", String]
  type Title = AttributeModifier["title", String]
  type Translate = AttributeModifier["translate", Boolean]
  type Unselectable = AttributeModifier["unselectable", Boolean]
  type WidthAttr = AttributeModifier["width", Int]
  type Xmlns = AttributeModifier["xmlns", String]
